### ISSUE TITLE
WIndow decorations color

### ISSUE THREAD

**Issue by ciolansteen** [WhitewaterFoundry/pengwin-setup#241]
Windows decoration not respecting OS's dark / light theme for Windowed Apps mode and Floating Desktop

Expecting behaviour - change titlebar's color when changing windows theme.

![image](https://user-images.githubusercontent.com/8395752/88505288-c2bc5300-cfdf-11ea-8973-9311857313e2.png)

**Comment by crramirez** [comment]
Hello,

Thanks for reporting. We have no control over this because it is a Window generated by the XServer. We will look if we can do something about this in the future, like using Linux theme decorations.

Meanwhile, I think you could find this interesting: https://www.onmsft.com/how-to/how-to-get-dark-theme-title-bars-in-windows-10-without-changing-your-accent-colour

Regards,
Carlos
